Repository AliyunContainerService/kube-eventer, pull requests merged in 2019-08, with the labels that each got.

#23 add wechat sink
  docs/en/wechat-sink.md
  sinks/factory.go
  sinks/wechat/wechat.go
  sinks/wechat/wechat_test.go
Labels: enhancement, good first issue

#19 Add MysqlSink
  common/mysql/OWNERS
  common/mysql/mysql.go
  common/mysql/shema.sql
  docs/en/mysql-sink.md
  go.mod
  go.sum
  sinks/factory.go
  sinks/mysql/OWNERS
  sinks/mysql/mysql.go
  vendor/github.com/go-sql-driver/mysql/.gitignore
  vendor/github.com/go-sql-driver/mysql/.travis.yml
  vendor/github.com/go-sql-driver/mysql/AUTHORS
  vendor/github.com/go-sql-driver/mysql/CHANGELOG.md
  vendor/github.com/go-sql-driver/mysql/CONTRIBUTING.md
  vendor/github.com/go-sql-driver/mysql/LICENSE
  vendor/github.com/go-sql-driver/mysql/README.md
  vendor/github.com/go-sql-driver/mysql/appengine.go
  vendor/github.com/go-sql-driver/mysql/auth.go
  vendor/github.com/go-sql-driver/mysql/buffer.go
  vendor/github.com/go-sql-driver/mysql/collations.go
  vendor/github.com/go-sql-driver/mysql/connection.go
  vendor/github.com/go-sql-driver/mysql/connection_go18.go
  vendor/github.com/go-sql-driver/mysql/const.go
  vendor/github.com/go-sql-driver/mysql/driver.go
  vendor/github.com/go-sql-driver/mysql/dsn.go
  vendor/github.com/go-sql-driver/mysql/errors.go
  vendor/github.com/go-sql-driver/mysql/fields.go
  vendor/github.com/go-sql-driver/mysql/infile.go
  vendor/github.com/go-sql-driver/mysql/packets.go
  vendor/github.com/go-sql-driver/mysql/result.go
  vendor/github.com/go-sql-driver/mysql/rows.go
  vendor/github.com/go-sql-driver/mysql/statement.go
  vendor/github.com/go-sql-driver/mysql/transaction.go
  vendor/github.com/go-sql-driver/mysql/utils.go
  vendor/github.com/go-sql-driver/mysql/utils_go17.go
  vendor/github.com/go-sql-driver/mysql/utils_go18.go
  vendor/google.golang.org/appengine/cloudsql/cloudsql.go
  vendor/google.golang.org/appengine/cloudsql/cloudsql_classic.go
  vendor/google.golang.org/appengine/cloudsql/cloudsql_vm.go
  vendor/modules.txt
Labels: enhancement

#30 Fix `annotations` indent
  README.md
Labels: LGTM, documentation
